# Generated by Django 5.2.8 on 2025-12-15 16:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Esame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('materia', models.CharField(max_length=100)),
                ('voto', models.DecimalField(decimal_places=2, max_digits=4)),
                ('data_esame', models.DateField()),
                ('cfu', models.IntegerField(default=6)),
                ('studente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demo.studente')),
            ],
        ),
    ]
